# Generated by Django 4.0.4 on 2022-05-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommersApp', '0004_alter_product_product_image_product_multimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_multimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommersApp.product'),
        ),
    ]
